name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnotify-dev libusb-1.0-0-dev gcc pkg-config  # Install the necessary packages

    #
    # - name: configure
    #   run: ./configure
    #
    - name: Install dependencies
      run: make
    #
    # - name: Run check
    #   run: make check
    #
    # - name: Run distcheck
    #   run: make distcheck
    # - name: Run tests (if applicable)
    #   run: |
    #     # Run your tests or any post-build actions here
    #     echo "Running tests..."
    #     ./awcc
